services:
  redis:
    image: redis:latest 
    container_name: api-chat-redis
    ports:
      - "6379:6379" 
  postgres:
    image: postgres:15
    container_name: api-chat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api-chat:
    build: .
    container_name: api-chat
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      # БД и Redis
      # Use docker-specific URL to avoid .env DATABASE_URL pointing to 127.0.0.1
      DATABASE_URL: ${DATABASE_URL_DOCKER:-postgresql://chat_user:chat_pass@postgres:5432/chat_db?schema=public}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      # Приложение
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      RSA_KEK_PRIVATE_KEY_PEM: ${RSA_KEK_PRIVATE_KEY_PEM}
      RSA_KEK_PUBLIC_KEY_PEM: ${RSA_KEK_PUBLIC_KEY_PEM}
      MASTER_KEK_WRAPPED_B64: ${MASTER_KEK_WRAPPED_B64}
      CHAT_PUBLIC_KEY_PEM: ${CHAT_PUBLIC_KEY_PEM}
      RSA_KEK_KEY_ID: ${RSA_KEK_KEY_ID}

    ports:
      - "3000:3000"
    volumes:
      - uploads:/usr/src/app/uploads
    command: ["node", "dist/src/main.js"]

volumes:
  db-data:
  uploads:
